import { int, json, mysqlEnum, mysqlTable, text, timestamp, varchar } from "drizzle-orm/mysql-core";

/**
 * Core user table backing auth flow.
 */
export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(),
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

/**
 * War Room sessions — each analysis run creates one session.
 */
export const sessions = mysqlTable("sessions", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  /** Original document title */
  documentTitle: varchar("documentTitle", { length: 512 }).notNull(),
  /** The uploaded document content (text extracted) */
  documentContent: text("documentContent").notNull(),
  /** Context form data: industry, company size, stakeholder archetypes */
  contextData: json("contextData"),
  /** Overall robustness score (0-100) */
  robustnessScore: int("robustnessScore"),
  /** Session status */
  status: mysqlEnum("status", ["uploading", "researching", "generating", "complete", "error"]).default("uploading").notNull(),
  /** Whether unhinged mode was toggled */
  unhingedMode: mysqlEnum("unhingedMode", ["off", "on"]).default("off").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Session = typeof sessions.$inferSelect;
export type InsertSession = typeof sessions.$inferInsert;

/**
 * AI-generated personas for each session.
 */
export const personas = mysqlTable("personas", {
  id: int("id").autoincrement().primaryKey(),
  sessionId: int("sessionId").notNull(),
  /** Persona archetype name, e.g. "The Risk-Averse CFO" */
  name: varchar("name", { length: 256 }).notNull(),
  /** Role title, e.g. "Chief Financial Officer" */
  role: varchar("role", { length: 256 }).notNull(),
  /** One-line perspective description */
  perspective: text("perspective").notNull(),
  /** Industry research context injected into this persona */
  researchContext: text("researchContext"),
  /** Avatar style identifier */
  avatarStyle: varchar("avatarStyle", { length: 64 }),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type Persona = typeof personas.$inferSelect;
export type InsertPersona = typeof personas.$inferInsert;

/**
 * Critiques generated by each persona, filtered by the Moderator.
 */
export const critiques = mysqlTable("critiques", {
  id: int("id").autoincrement().primaryKey(),
  sessionId: int("sessionId").notNull(),
  personaId: int("personaId").notNull(),
  /** Critique title, e.g. "Revenue Projection Vulnerability" */
  title: varchar("title", { length: 512 }).notNull(),
  /** The attack — what's wrong with the document */
  attack: text("attack").notNull(),
  /** The citation — evidence backing the critique */
  citation: text("citation"),
  /** URL source for the citation */
  citationUrl: varchar("citationUrl", { length: 1024 }),
  /** The suggested fix */
  suggestedFix: text("suggestedFix").notNull(),
  /** Risk severity */
  severity: mysqlEnum("severity", ["high", "medium", "low"]).notNull(),
  /** Confidence score (0-100) */
  confidenceScore: int("confidenceScore").notNull(),
  /** Confidence explanation for tooltip */
  confidenceReason: text("confidenceReason"),
  /** Unhinged mode version of the attack */
  unhingedAttack: text("unhingedAttack"),
  /** Section of the document this critique references */
  documentSection: varchar("documentSection", { length: 256 }),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type Critique = typeof critiques.$inferSelect;
export type InsertCritique = typeof critiques.$inferInsert;

/**
 * Research log entries — for the Live Research Terminal display.
 */
export const researchLogs = mysqlTable("researchLogs", {
  id: int("id").autoincrement().primaryKey(),
  sessionId: int("sessionId").notNull(),
  /** Log message displayed in the terminal */
  message: text("message").notNull(),
  /** Log type for styling */
  logType: mysqlEnum("logType", ["search", "analyze", "inject", "complete", "error"]).default("search").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type ResearchLog = typeof researchLogs.$inferSelect;
export type InsertResearchLog = typeof researchLogs.$inferInsert;
